_isCalledByPlayer = [_this,0,0,[0]] call BIS_fnc_param;
/*
if (_isCalledByPlayer!=1) then {
	sleep 120;
};
*/
					playSound "Alarm";
					hintSilent parseText "<t size=""1.1"">Erdbeben Gefahrenstufe:</t><br/><t color=""#40FF00"" t size=""2"">NIEDRIG</t>";
					sleep 3;
					playSound "Earthquake_01";
					enableCamShake true;
					addCamShake [7, 11, 10];
					sleep 30;
					playSound "Alarm";
					hintSilent parseText "<t size=""1.1"">Erdbeben Gefahrenstufe:</t><br/><t color =""#FFFF00"" t size = ""2"">MITTEL</t>";
					sleep 3;
					playSound "Earthquake_01";
					enableCamShake true;
					addCamShake [7, 11, 10];
					sleep 30;
					playSound "Alarm";
					hintSilent parseText "<t size=""1.1"">Erdbeben Gefahrenstufe:</t><br/><t color = ""#FF8000"" t size = ""2"">HOCH</t>";
					sleep 3;
					playSound "Earthquake_04";
					enableCamShake true;
					sleep 1;
					addCamShake[10, 12, 15];
					sleep 30;
					playSound "Alarm";
					hintSilent parseText "<t size=""1.1"">Erdbeben Gefahrenstufe:</t><br/><t color = ""#FF0000"" t size = ""2"">KRITISCH</t>";
					sleep 3;
					playSound "Alarm";
					sleep 1;
					playSound "Alarm";
					sleep 1;
					playSound "Earthquake_04";
					addCamShake [10, 20, 20];
					sleep 6;
					playSound "Alarm";
					sleep 1;
					playSound "Alarm";
					sleep 1;
					playSound "Earthquake_04";
					addCamShake [10, 20, 20];
					sleep 6;
					playSound "Earthquake_04";
					addCamShake [10, 20, 20];
					sleep 30;
					enableCamShake false;
					sleep 10;
					
[]execVM "core\functions\fn_nuke.sqf";					